#!/usr/bin/env python3
"""Record one run of main in the benchmark history, and regenerate its report.

    history.py --results results.json --data-dir bench-data

Appends the run as one JSON line to DATA_DIR/history.jsonl and rewrites
DATA_DIR/README.md: for every operation, the last runs of main as a table,
one column per measure, and a trend marker per measure. The performance job
runs this on each merge to main, in a worktree of the orphan `bench-data`
branch (SWR-PERF-0007).

Standard library only.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

WINDOW = 30

MEASURES = (
    "instructions", "allocations", "allocated_bytes", "retained_bytes",
    "binary_bytes", "wall_ns", "cpu_ns",
)

# Below this change across the window a measure reads as flat. Instruction
# counts wobble by well under this between identical runs.
FLAT_PERCENT = 0.5


def append(results: dict, history: Path) -> None:
    record = {
        "git_sha": results.get("git_sha", "unknown"),
        "date": results.get("date", "unknown"),
        "toolchain": results.get("toolchain", {}),
        "measurements": results.get("measurements", {}),
    }
    with history.open("a", encoding="utf-8") as out:
        out.write(json.dumps(record, sort_keys=True, separators=(",", ":")) + "\n")


def load(history: Path) -> list[dict]:
    if not history.is_file():
        return []
    return [json.loads(line) for line in history.read_text(encoding="utf-8").splitlines()
            if line.strip()]


def trend(values: list[float]) -> str:
    """'up', 'down' or 'flat', with the change from the first to the last run
    in the window."""
    present = [v for v in values if v is not None]
    if len(present) < 2:
        return "flat"
    first, last = present[0], present[-1]
    if first == 0:
        return "flat" if last == 0 else "up (from 0)"
    change = (last - first) * 100.0 / first
    if abs(change) < FLAT_PERCENT:
        return "flat"
    return f"{'up' if change > 0 else 'down'} {change:+.1f}%"


def fmt(value) -> str:
    if value is None:
        return "-"
    if isinstance(value, float) and not value.is_integer():
        return f"{value:,.1f}"
    return f"{int(value):,}"


def render(runs: list[dict]) -> str:
    window = runs[-WINDOW:]
    lines = [
        "# Benchmark history of main",
        "",
        "Generated by `bench/perf/history.py` on every merge to main; do not edit by hand.",
        f"Each table shows the last {len(window)} of {len(runs)} runs, oldest first.",
        "The raw records are in `history.jsonl`, one line per run.",
        "The trend compares the first and the last run in the window;",
        f"a change under {FLAT_PERCENT}% reads as flat.",
        "",
    ]
    if window:
        toolchain = window[-1].get("toolchain") or {}
        lines += [
            f"Latest run: `{window[-1].get('git_sha', '?')[:12]}` on {window[-1].get('date', '?')}, "
            f"{toolchain.get('arch', '?')}, {toolchain.get('compiler', '?')}.",
            "",
        ]
    ids = sorted({op_id for run in window for op_id in run.get("measurements", {})})
    for op_id in ids:
        series = [run.get("measurements", {}).get(op_id, {}) for run in window]
        measures = [m for m in MEASURES if any(m in s for s in series)]
        lines += [f"## `{op_id}`", ""]
        trends = ", ".join(f"{m} {trend([s.get(m) for s in series])}" for m in measures)
        lines += [f"Trend: {trends}.", ""]
        lines.append("| sha | date | " + " | ".join(measures) + " |")
        lines.append("|---|---|" + "--:|" * len(measures))
        for run, values in zip(window, series):
            cells = " | ".join(fmt(values.get(m)) for m in measures)
            lines.append(f"| `{run.get('git_sha', '?')[:12]}` | {run.get('date', '?')[:10]} | {cells} |")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--results", type=Path, required=True)
    parser.add_argument("--data-dir", type=Path, required=True)
    args = parser.parse_args(argv)

    args.data_dir.mkdir(parents=True, exist_ok=True)
    history = args.data_dir / "history.jsonl"
    append(json.loads(args.results.read_text()), history)
    (args.data_dir / "README.md").write_text(render(load(history)), encoding="utf-8")
    print(f"history: {len(load(history))} runs in {history}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
